# Generated by Django 4.0.5 on 2022-07-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bookdesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='images',
            name='isTrending',
            field=models.BooleanField(default=False),
        ),
    ]
