# Generated by Django 4.0.5 on 2022-07-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_images_isfeatured_images_istrending'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='showFeatured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='showTrending',
            field=models.BooleanField(default=False),
        ),
    ]
