# Generated by Django 4.0.5 on 2022-07-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_room_showfeatured_room_showtrending'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='profilePic',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.URLField(),
        ),
    ]
