# Generated by Django 4.0.5 on 2022-07-25 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bookdesign_created_at_booksession_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='mainDivBackImageUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgUrl', models.URLField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
        ),
        migrations.AddField(
            model_name='bookdesign',
            name='interestedServiceDesign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.serviceimage'),
        ),
    ]
