# Generated by Django 4.0.5 on 2022-07-25 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_service_maindivbackimageurl_serviceimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdesign',
            name='interestedDesign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.images'),
        ),
        migrations.AlterField(
            model_name='bookdesign',
            name='interestedServiceDesign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.serviceimage'),
        ),
    ]
